# Generated by Django 5.1.3 on 2025-01-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
            ],
        ),
    ]
