# Generated by Django 4.2.16 on 2025-01-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='products',
            field=models.ManyToManyField(null=True, related_name='products', to='app.product'),
        ),
    ]
