# Generated by Django 4.2.16 on 2025-01-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_seller_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.product'),
        ),
    ]
