# Generated by Django 4.2.16 on 2025-01-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_seller_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
