# Generated by Django 5.1.2 on 2025-01-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_title_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
