# Generated by Django 4.2.16 on 2025-01-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_name_product_p_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='name',
        ),
    ]
