# Generated by Django 5.1.2 on 2025-01-06 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_product_price"),
        ("app", "0009_rename_p_name_product_name"),
    ]

    operations = []
